name: Rust CI

on:
  pull_request:
    branches: [ main ]

jobs:
  rust-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Build project
      run: cargo build --verbose

    - name: Run Clippy (pedantic)
      run: cargo clippy --workspace -- -W clippy::pedantic

    - name: Install Vulkan software dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libvulkan1 mesa-vulkan-drivers vulkan-tools

    - name: Run unit tests
      run: cargo test --workspace --verbose

    - name: Run graphic tests
      env:
        WGPU_BACKEND: vulkan
      run: cargo run -p graphic-tests -- --test-name all --graphic-api wgpu
